name: AURAPOS Automation Tests

on:
  push:
    branches: [ main ]

jobs:
  automation-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        cd client && npm install
        cd ../backend && npm install
        cd .. && npm ci

    - name: Start Backend Server
      run: |
        cd backend
        npm start &
        echo "Backend server starting..."
        sleep 20
      working-directory: ./
        
    - name: Start Frontend
      run: |
        cd client
        npm start &
        echo "Frontend starting..."
        sleep 40
      working-directory: ./
        
    - name: Run Automation Tests
      run: |
        google-chrome --version
        node tests/ui/login-working-test.js
        sleep 5
        node tests/ui/add-to-cart-working.js
      env:
        NODE_ENV: test
        
    - name: Cleanup
      if: always()
      run: |
        pkill -f node || true
        echo "Cleanup completed"
        
    - name: Success Report
      if: always()
      run: |
        echo "=================================================================="
        echo "AURAPOS AUTOMATION TESTS COMPLETED"
        echo "=================================================================="
        echo "AUTOMATION TESTS: Selenium UI Testing"
        echo "Login: Without validation middleware"
        echo "=================================================================="