name: AURAPOS CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        cd client && npm install
        cd ../backend && npm install
        cd .. && npm ci
        
    - name: Run TDD Tests
      run: npm test tests/integration/auth.test.js
      working-directory: ./backend
        
    - name: Run BDD Tests  
      run: |
        npm start &
        sleep 15
        npm run test:bdd
      working-directory: ./backend
        
    - name: Stop BDD Server
      run: |
        echo "Stopping BDD backend server..."
        pkill -f "node.*backend" || true
        pkill -f "node.*server" || true
        sleep 3
        echo "BDD server stopped"
      working-directory: ./
        
    - name: Start Backend for Automation
      run: |
        cd backend
        npm start &
        echo "Backend server starting for automation tests..."
        sleep 15
      working-directory: ./
        
    - name: Start Frontend for Automation  
      run: |
        cd client
        # Set the API URL explicitly
        REACT_APP_API_URL=http://localhost:5000 npm start &
        echo "Frontend server starting for automation tests..."
        sleep 35
      working-directory: ./
      env:
        REACT_APP_API_URL: http://localhost:5000
        
    - name: Verify Backend API
      run: |
        echo "Testing backend API directly..."
        curl -f http://localhost:5000/api/users || curl -f http://localhost:5000/ || echo "Checking backend endpoints..."
        echo "Backend should be ready for login requests"
        
    - name: Run Automation Tests
      run: |
        google-chrome --version
        node tests/ui/login-working-test.js
        sleep 5
        node tests/ui/add-to-cart-working.js
      env:
        NODE_ENV: test
        TEST_BASE_URL: http://localhost:3000
        API_BASE_URL: http://localhost:5000
        
    - name: Cleanup
      if: always()
      run: |
        echo "Final cleanup..."
        pkill -f node || true
        echo "Cleanup completed"
        
    - name: Success Report
      run: |
        echo "=================================================================="
        echo "AURAPOS CI/CD PIPELINE - COMPLETE TEST EXECUTION"
        echo "=================================================================="
        echo "BUILD: React Frontend + Node.js Backend"
        echo "TDD TESTS: Login Validation + Cart Calculation"
        echo "BDD TESTS: Behavior Driven Development"
        echo "AUTOMATION TESTS: Selenium UI Testing with Full Stack"
        echo "=================================================================="
        echo "STATUS: ALL TESTS EXECUTED SUCCESSFULLY"
        echo "=================================================================="