name: AURAPOS CI/CD - Build Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Install backend dependencies
      run: npm install
      working-directory: ./backend
        
    - name: Install frontend dependencies
      run: npm install
      working-directory: ./client
        
    - name: Build React application
      run: CI=false npm run build
      working-directory: ./client
        
    - name: Verify build
      run: |
        echo "BUILD PROCESS COMPLETED"
        echo "Backend dependencies installed"
        echo "Frontend dependencies installed"
        echo "React application built"
        
        if [ -d "client/build" ]; then
          echo "Build artifacts created successfully"
        else
          echo "Build failed - no build directory"
          exit 1
        fi

    - name: Build Report
      run: |
        echo "AURAPOS CI/CD BUILD PIPELINE - SUCCESS"
        echo "PROJECT BUILD COMPLETED"
        echo "Frontend: React application built"
        echo "Backend: Node.js dependencies installed"
        echo "Build artifacts are ready for deployment"