name: AURAPOS CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        cd client && npm install
        cd ../backend && npm install
        cd .. && npm ci
        
    - name: Run TDD Tests
      run: npm test tests/integration/auth.test.js
      working-directory: ./backend
        
    - name: Run BDD Tests  
      run: |
        npm start &
        sleep 15
        npm run test:bdd
      working-directory: ./backend
        
    - name: Stop BDD Server
      run: |
        echo "Stopping BDD backend server..."
        pkill -f "node.*backend" || true
        pkill -f "node.*server" || true
        sleep 3
        echo "BDD server stopped"
      working-directory: ./
        
    - name: Start Backend for Automation
      run: |
        cd backend
        npm start &
        echo "Backend server starting for automation tests..."
        sleep 15
      working-directory: ./
        
    - name: Start Frontend for Automation  
      run: |
        cd client
        npm start &
        echo "Frontend server starting for automation tests..."
        sleep 30
      working-directory: ./
        
    - name: Verify Servers Running
      run: |
        echo "Checking servers before automation tests:"
        echo "Backend process:" && ps aux | grep "node.*backend" | grep -v grep || echo "No backend process"
        echo "Frontend process:" && ps aux | grep "node.*client" | grep -v grep || echo "No frontend process"
        echo "Port 5000 (backend):" && (netstat -tuln | grep :5000 || echo "Not found")
        echo "Port 3000 (frontend):" && (netstat -tuln | grep :3000 || echo "Not found")
        
    - name: Run Automation Tests
      run: |
        google-chrome --version
        node tests/ui/login-working-test.js
        sleep 5
        node tests/ui/add-to-cart-working.js
      env:
        NODE_ENV: test
        
    - name: Cleanup
      if: always()
      run: |
        echo "Final cleanup..."
        pkill -f node || true
        echo "Cleanup completed"
        
    - name: Success Report
      run: |
        echo "=================================================================="
        echo "AURAPOS CI/CD PIPELINE - COMPLETE TEST EXECUTION"
        echo "=================================================================="
        echo "BUILD: React Frontend + Node.js Backend"
        echo "TDD TESTS: Login Validation + Cart Calculation"
        echo "BDD TESTS: Behavior Driven Development"
        echo "AUTOMATION TESTS: Selenium UI Testing with Full Stack"
        echo "=================================================================="
        echo "STATUS: ALL TESTS EXECUTED SUCCESSFULLY"
        echo "=================================================================="